### ISSUE TITLE
Attach snap disk to bkpvm

### ISSUE THREAD

**Issue by jhquentin** [vacosta94/VirtBKP#14]
[root@ovirtengine VirtBKP]# /opt/VirtBKP/backup_vm.py /opt/VirtBKP/default.conf ubuntu16
[OK] Connection to oVIrt API success https://ovirtengine.iquentin.cz/ovirt-engine/api
[INFO] Trying to create snapshot of VM: 31a96f96-b9bf-404a-aa04-00d601e39b82
[INFO] Waiting until snapshot creation ends
[INFO] Waiting until snapshot creation ends
[OK] Snapshot created
[INFO] Trying to create a qcow2 file of disk 6b2681de-271d-4c19-9b14-26857d44d0e8
[INFO] Attach snap disk to bkpvm
Traceback (most recent call last):
  File "/opt/VirtBKP/backup_vm.py", line 6, in <module>
    b.main()
  File "/opt/VirtBKP/backup_vm_last.py", line 241, in main
    self.backup(self.vmid,self.snapid,disk_id,self.bkpvm)
  File "/opt/VirtBKP/backup_vm_last.py", line 209, in backup
    self.attach_disk(bkpvm,disk_id,snapid)
  File "/opt/VirtBKP/backup_vm_last.py", line 120, in attach_disk
    urlattach = self.url+"/v3/vms/"+bkpid+"/disks/"

**Comment by jhquentin** [comment]
bkpvm           = bkpvm
can you explain me please this?

**Comment by BjarnBachmanVC** [comment]
> bkpvm = bkpvm
> can you explain me please this?

bkpvm           = Your_DataCenter_Name_Of_BackupVM

My interpretation anyway

**Comment by jhquentin** [comment]
Ok, so I ame correct, that I have putted there the Name of Data Center.
thank you
Can you please the error please?
I can participate in testing

**Comment by BjarnBachmanVC** [comment]
I'm not sure I can fix. I am just Using the sw. And it is working for me with the patch that I proposed in https://github.com/vacosta94/VirtBKP/pull/13 .
However this could be a different problem from what I was experiencing. 
Try to apply the patch in pull 13. This will be needed anyway.

Then the configuration file for vacostas backup solution I have documented internally our company as
Fields
[bkp]
url             = https://OUR_FDQN_NAME_OF_ENGINE/ovirt-engine/api
user            = admin@internal [admin user you are running as]
password        = admin_engine_password
ca_file         = /opt/VirtBKPca.crt
bkpvm           = Your_DataCenter_Name_of_the_backupvm
bckdir          = /var/lib/ovirt-vm-backup/ [or whatever path you have]

[restore]
url             = https://OUR_FDQN_NAME_OF_ENGINE/ovirt-engine/api
user            = admin@internal
password        = your_engine_password
ca_file         = /opt/VirtBKPca.crt
storage         = OUR_EXPORT_DOMAIN_NAME
proxy           = OUR_FDQN_NAME_OF_ENGINE
proxyport       = 54323 [or the port you are using]

Make sure that firewall is configured according to ovirt spec.

**Comment by vacosta94** [comment]
Hi 
The bkpvm should be name of the VM where you're runnning the script
Keep in mind that the bkpvm should be on the same datacenter of the VM that you want to create a backup of

**Comment by nevesigor** [comment]
@jhquentin don't expose your ovirt management interface online and even less anouce it on public!
