### ISSUE TITLE
Upload Disk failure

### ISSUE THREAD

**Issue by pdclouds** [vacosta94/VirtBKP#16]
Hi,

Many thanks for sharing you backup solution.

We've come across an issue when trying to restore a backup, please refer to below output, we ran script several times and it fails at the 13% mark, the qcow2 is 7GB and also backupVM live in same cluster, are you able to assist;

Also noticed transfer failed at 1020 or 1024 bytes....

200 OK Completed 13%
200 OK Completed 13%
200 OK Completed 13%
200 OK Completed 13%
Traceback (most recent call last):
  File "/opt/vmProtect/upload_disk.py", line 139, in <module>
    headers=upload_headers,
  File "/usr/lib64/python2.7/httplib.py", line 1056, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1090, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1052, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 890, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 866, in send
    self.sock.sendall(data)
  File "/usr/lib64/python2.7/ssl.py", line 744, in sendall
    v = self.send(data[count:])
  File "/usr/lib64/python2.7/ssl.py", line 710, in send
    v = self._sslobj.write(data)
socket.error: [Errno 32] Broken pipe

**Comment by vacosta94** [comment]
Hi, please check if you have the last version

Also please check and share the logs of the imageio proxy
