### ISSUE TITLE
Error when backup.  ovirtsdk4.Error: Error while sending HTTP request

### ISSUE THREAD

**Issue by txsastre** [vacosta94/VirtBKP#2]
hi, I was trying this project.
I have 2 problems
wget --insecure is deprecated, I used --no-check-certificate and then renamed to ca.crt

then, once run I have this error

```
[root@bkpvm VirtBKP]# /opt/VirtBKP/backup_vm.py /opt/VirtBKP/default.conf lubuntu1
[OK] Connection to oVIrt API success https://ovirtengine/ovirt-engine/api
Traceback (most recent call last):
  File "/opt/VirtBKP/backup_vm.py", line 231, in <module>
    main()
  File "/opt/VirtBKP/backup_vm.py", line 214, in main
    vmid = get_id_vm(vmname)
  File "/opt/VirtBKP/backup_vm.py", line 51, in get_id_vm
    vms = vm_service.list()
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/services.py", line 27900, in list
    return self._internal_get(headers, query, wait)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 193, in _internal_get
    context = self._connection.send(request)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/__init__.py", line 336, in send
    sys.exc_info()[2]
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/__init__.py", line 331, in send
    return self.__send(request)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/__init__.py", line 353, in __send
    self._sso_token = self._get_access_token()
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/__init__.py", line 578, in _get_access_token
    sso_response = self._get_sso_response(self._sso_url, post_data)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/__init__.py", line 645, in _get_sso_response
    curl.perform()
ovirtsdk4.Error: Error while sending HTTP request


```

**Comment by vacosta94** [comment]
Hello txsastre, that error is caused by ssl check, can you please try to use your ovirt's fqdn as URL instead hostname, also i'll work to improve ouputs for this kind of errors

**Comment by txsastre** [comment]
hi. on ovirt engine i've done
`hotsname -f"
i received this
ovirtengine.local`

changed on bkpvm machine in default.conf but I have the same error
```
[root@bkpvm VirtBKP]# /opt/VirtBKP/backup_vm.py /opt/VirtBKP/default.conf lubuntu1
[OK] Connection to oVIrt API success https://ovirtengine.local/ovirt-engine/api
Traceback (most recent call last):
  File "/opt/VirtBKP/backup_vm.py", line 231, in <module>
    main()
  File "/opt/VirtBKP/backup_vm.py", line 214, in main
    vmid = get_id_vm(vmname)
  File "/opt/VirtBKP/backup_vm.py", line 51, in get_id_vm
    vms = vm_service.list()
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/services.py", line 27900, in list
    return self._internal_get(headers, query, wait)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 193, in _internal_get
    context = self._connection.send(request)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/__init__.py", line 336, in send
    sys.exc_info()[2]
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/__init__.py", line 331, in send
    return self.__send(request)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/__init__.py", line 353, in __send
    self._sso_token = self._get_access_token()
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/__init__.py", line 578, in _get_access_token
    sso_response = self._get_sso_response(self._sso_url, post_data)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/__init__.py", line 645, in _get_sso_response
    curl.perform()
ovirtsdk4.Error: Error while sending HTTP request
[root@bkpvm VirtBKP]# 

```

**Comment by txsastre** [comment]
I typed hostname -f , it has given me "ovirtengine.local"

so I replaced the "ovirtengine" to "ovirtengine.local" and at this moment it seems to be working
theres a message saying "identifying disk device it can be a while"

it has been waiting to identify the device for almost 30' I stopped it, changed the kind of disk to the backup machine and tried again. from virtio-scsi to virtio 

I can see that there is attached a dist in /dev/vdb but its still "identifying disk device" for ever.

**Comment by vacosta94** [comment]
do you have ovirt-guest-agent installed on bkpvm?

**Comment by txsastre** [comment]
yes 1.0.14 .

> El paquet ovirt-guest-agent-common-1.0.14-1.el7.noarch ja es troba instal·lat i en l'última versió.


it was installed following your intructions.

**Comment by txsastre** [comment]
CTRL-C to stop the "waiting disk"
```
[root@bkpvm VirtBKP]#   File "/opt/VirtBKP/backup_vm.py", line 231, in <module>
-bash: hi ha un error inesperat de sintaxi prop del senyal 'newline'
[root@bkpvm VirtBKP]#     main()
>   File "/opt/VirtBKP/backup_vm.py", line 226, in main
-bash: hi ha un error inesperat de sintaxi prop del senyal 'File'
[root@bkpvm VirtBKP]#     backup(vmid,snapid,disk_id,bkpvm)
-bash: hi ha un error inesperat de sintaxi prop del senyal 'vmid,snapid,disk_id,bkpvm'
[root@bkpvm VirtBKP]#   File "/opt/VirtBKP/backup_vm.py", line 193, in backup
-bash: File: no s'ha trobat l'ordre
[root@bkpvm VirtBKP]#     dev = get_logical_disk(bkpvm,disk_id)
-bash: hi ha un error inesperat de sintaxi prop del senyal '('
[root@bkpvm VirtBKP]#   File "/opt/VirtBKP/backup_vm.py", line 153, in get_logical_disk
-bash: File: no s'ha trobat l'ordre
[root@bkpvm VirtBKP]#     time.sleep(1)
-bash: hi ha un error inesperat de sintaxi prop del senyal '1'



```
disk attached at the moment
```
[root@bkpvm VirtBKP]# [root@bkpvm VirtBKP]# ls /dev/vd
[root@bkpvm VirtBKP]# vda   vda1  vda2  vdb   vdb1  vdb2  vdb5

```

**Comment by txsastre** [comment]
also tracing your code
I removed some comments and added a few "prints" to see whats happening

thats an example
seam that when it has the same diskid it does not have the device /dev/vda (that's were is attached).

EDIT. more clear 
```
[INFO] Attach snap disk to bkpvm
[INFO] Identifying disk device, this might take a while
None
316d7633-6197-4c12-b982-9ab5607d3a3f
316d7633-6197-4c12-b982-9ab5607d3a3f
./dev/sda
6c539c20-fa96-4241-88cd-76174c412abb
316d7633-6197-4c12-b982-9ab5607d3a3f
.None
316d7633-6197-4c12-b982-9ab5607d3a3f
316d7633-6197-4c12-b982-9ab5607d3a3f
./dev/sda
6c539c20-fa96-4241-88cd-76174c412abb
316d7633-6197-4c12-b982-9ab5607d3a3f
.None
316d7633-6197-4c12-b982-9ab5607d3a3f
316d7633-6197-4c12-b982-9ab5607d3a3f
./dev/sda
6c539c20-fa96-4241-88cd-76174c412abb
316d7633-6197-4c12-b982-9ab5607d3a3f
.None
316d7633-6197-4c12-b982-9ab5607d3a3f
316d7633-6197-4c12-b982-9ab5607d3a3f
./dev/sda
6c539c20-fa96-4241-88cd-76174c412abb
316d7633-6197-4c12-b982-9ab5607d3a3f
.None
316d7633-6197-4c12-b982-9ab5607d3a3f
316d7633-6197-4c12-b982-9ab5607d3a3f
./dev/sda
6c539c20-fa96-4241-88cd-76174c412abb
316d7633-6197-4c12-b982-9ab5607d3a3f
.None
316d7633-6197-4c12-b982-9ab5607d3a3f
316d7633-6197-4c12-b982-9ab5607d3a3f
./dev/sda
6c539c20-fa96-4241-88cd-76174c412abb
316d7633-6197-4c12-b982-9ab5607d3a3f
...


```

gracias

**Comment by txsastre** [comment]
finally I hard coded my disk logical name and changed the code
from this
`   if disk.id == diskid and str(dev) != "None":`

to this 
`dev="/dev/vda  #hard coded logical disk"
   if disk.id == diskid and dev != "None":`

and it has worked.

**Comment by vacosta94** [comment]
great! i'm happy it works 

I'll try to improve device identification process as well, so can you please give more details about your environment:
- oVirt version?
- bkpvm OS version?
- Are you sure ovirt-guest-agent service is running? if the service is not running it wouldn't identify disk

**Comment by txsastre** [comment]
well I've made it work, but I think is not the correct way


 >  **-     oVirt version?
 
  last version 4.2.1
 
 > -     bkpvm OS version?
 
  last version. reinstalled right now
 > -     Are you sure ovirt-guest-agent service is running? if the service is not running it wouldn't identify disk**
 
  ` ovirt-guest-agent-common-1.0.14-1.el7.noarch``
 ```
[root@bkpvm ~]# ps ax | grep ovirt
  671 ?        Ssl    0:01 /usr/bin/python /usr/share/ovirt-guest-agent/ovirt-guest-agent.py
```


Operating System : CentOS 7

**Comment by txsastre** [comment]
also I have downgraded ovirt-guest-agent to version 1.0.13 and the same error is happening.

beginning to think that the problem is in the ovirt-engine, because I am also testing this other project https://github.com/zipurman/oVIRT_Simple_Backup/issues/6#issuecomment-376078068 and also having similar issues

**Comment by txsastre** [comment]
well I have upgraded the machine. ovirt 4.2.2.  ovirt-guest-agent 1.0.14 same issue.

![seleccio_021](https://user-images.githubusercontent.com/10468371/38161977-09188052-34d9-11e8-8a2c-35eb985f00b4.png)

**Comment by txsastre** [comment]
t
