### ISSUE TITLE
Error vm_service.list

### ISSUE THREAD

**Issue by bylli79** [vacosta94/VirtBKP#9]
launching the command, I get the following error:

vms = vm_service.list ()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/services.py", line 34210, in list
    return self._internal_get (headers, query, wait)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 202, in _internal_get
    context = self._connection.send (request)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/__init__.py", line 370, in send
    return self .__ send (request)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/__init__.py", line 388, in __send
    self.authenticate ()
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/__init__.py", line 384, in authenticate
    self .__ PARSE_ERROR (s)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/__init__.py", line 932, in __parse_error
    six.reraise (clazz, clazz (error_msg), sys.exc_info () [2])
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/__init__.py", line 381, in authenticate
    self._sso_token = self._get_access_token ()
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/__init__.py", line 617, in _get_access_token
    sso_response = self._get_sso_response (self._sso_url, post_data)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/__init__.py", line 694, in _get_sso_response
    curl.perform ()
ovirtsdk4.Error: Error while sending HTTP request: (77, '')

what can I do?

Thank you

**Comment by vacosta94** [comment]
That looks like a wrong password issue, please try to change you password to something simple and try.

Also remember that the user name is user@domain, for internal users is @internal
